//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoAppFront.ServiceConsultaProyectos {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceConsultaProyectos.ConsultaProyectosWSSoap")]
    public interface ConsultaProyectosWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaProyectos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ConsultaProyectos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaProyectos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ConsultaProyectosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaProyectosWSSoapChannel : GoAppFront.ServiceConsultaProyectos.ConsultaProyectosWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaProyectosWSSoapClient : System.ServiceModel.ClientBase<GoAppFront.ServiceConsultaProyectos.ConsultaProyectosWSSoap>, GoAppFront.ServiceConsultaProyectos.ConsultaProyectosWSSoap {
        
        public ConsultaProyectosWSSoapClient() {
        }
        
        public ConsultaProyectosWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaProyectosWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaProyectosWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaProyectosWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ConsultaProyectos() {
            return base.Channel.ConsultaProyectos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ConsultaProyectosAsync() {
            return base.Channel.ConsultaProyectosAsync();
        }
    }
}
