//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoAppFront.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProyectoDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProyectoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private double MetaField;
        
        private System.DateTime FechaInicioField;
        
        private System.DateTime FechaFinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Meta {
            get {
                return this.MetaField;
            }
            set {
                if ((this.MetaField.Equals(value) != true)) {
                    this.MetaField = value;
                    this.RaisePropertyChanged("Meta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.AltaProyectoWSSoap")]
    public interface AltaProyectoWSSoap {
        
        // CODEGEN: Generating message contract since element name dto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Proyecto_InsertOrUpdate", ReplyAction="*")]
        GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateResponse Proyecto_InsertOrUpdate(GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Proyecto_InsertOrUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateResponse> Proyecto_InsertOrUpdateAsync(GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Proyecto_InsertOrUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Proyecto_InsertOrUpdate", Namespace="http://tempuri.org/", Order=0)]
        public GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateRequestBody Body;
        
        public Proyecto_InsertOrUpdateRequest() {
        }
        
        public Proyecto_InsertOrUpdateRequest(GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Proyecto_InsertOrUpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GoAppFront.ServiceReference2.ProyectoDTO dto;
        
        public Proyecto_InsertOrUpdateRequestBody() {
        }
        
        public Proyecto_InsertOrUpdateRequestBody(GoAppFront.ServiceReference2.ProyectoDTO dto) {
            this.dto = dto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Proyecto_InsertOrUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Proyecto_InsertOrUpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateResponseBody Body;
        
        public Proyecto_InsertOrUpdateResponse() {
        }
        
        public Proyecto_InsertOrUpdateResponse(GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Proyecto_InsertOrUpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Proyecto_InsertOrUpdateResult;
        
        public Proyecto_InsertOrUpdateResponseBody() {
        }
        
        public Proyecto_InsertOrUpdateResponseBody(int Proyecto_InsertOrUpdateResult) {
            this.Proyecto_InsertOrUpdateResult = Proyecto_InsertOrUpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AltaProyectoWSSoapChannel : GoAppFront.ServiceReference2.AltaProyectoWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AltaProyectoWSSoapClient : System.ServiceModel.ClientBase<GoAppFront.ServiceReference2.AltaProyectoWSSoap>, GoAppFront.ServiceReference2.AltaProyectoWSSoap {
        
        public AltaProyectoWSSoapClient() {
        }
        
        public AltaProyectoWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AltaProyectoWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AltaProyectoWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AltaProyectoWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateResponse GoAppFront.ServiceReference2.AltaProyectoWSSoap.Proyecto_InsertOrUpdate(GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateRequest request) {
            return base.Channel.Proyecto_InsertOrUpdate(request);
        }
        
        public int Proyecto_InsertOrUpdate(GoAppFront.ServiceReference2.ProyectoDTO dto) {
            GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateRequest inValue = new GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateRequest();
            inValue.Body = new GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateRequestBody();
            inValue.Body.dto = dto;
            GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateResponse retVal = ((GoAppFront.ServiceReference2.AltaProyectoWSSoap)(this)).Proyecto_InsertOrUpdate(inValue);
            return retVal.Body.Proyecto_InsertOrUpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateResponse> GoAppFront.ServiceReference2.AltaProyectoWSSoap.Proyecto_InsertOrUpdateAsync(GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateRequest request) {
            return base.Channel.Proyecto_InsertOrUpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateResponse> Proyecto_InsertOrUpdateAsync(GoAppFront.ServiceReference2.ProyectoDTO dto) {
            GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateRequest inValue = new GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateRequest();
            inValue.Body = new GoAppFront.ServiceReference2.Proyecto_InsertOrUpdateRequestBody();
            inValue.Body.dto = dto;
            return ((GoAppFront.ServiceReference2.AltaProyectoWSSoap)(this)).Proyecto_InsertOrUpdateAsync(inValue);
        }
    }
}
