CREATE PROCEDURE usp_DecreaseTries
	@usu varchar(24)
AS
BEGIN
	UPDATE USR01 SET USTRIES = USTRIES - 1 WHERE USRNAME=@usu
END

CREATE PROCEDURE usp_ResetTries
	@Usu varchar(24)
AS
BEGIN
	UPDATE USR01 SET USTRIES = 3 WHERE USRNAME=@Usu
END

CREATE PROCEDURE usp_BlockUser
	@usu varchar(24)
AS
BEGIN
	UPDATE USR01 SET ISBLOCKED = 'X' WHERE USRNAME=@usu
END

CREATE PROCEDURE DBO.usp_LoginValidation
	@usu varchar(24),
	@pass varchar(32)
AS
BEGIN
DECLARE @status int
IF((SELECT COUNT(*) FROM USR01 WHERE (USRNAME=@usu AND USPASS=@pass AND ( SELECT USTRIES FROM USR01 WHERE USRNAME=@usu)>0 AND (SELECT ISBLOCKED FROM USR01 WHERE USRNAME=@usu)=''))=1)
	SET @status = 1
ELSE
	SET @status = 0

IF(((SELECT USTRIES FROM USR01 WHERE USRNAME=@usu)=0) AND ((SELECT ISBLOCKED FROM USR01 WHERE USRNAME=@usu)=''))
	exec usp_BlockUser @usu
	SET @status = 0

IF(((SELECT USPASS from USR01 WHERE USRNAME=@usu)!=@pass) AND ((SELECT USTRIES FROM USR01 WHERE USRNAME=@usu)>0))
	exec usp_DecreaseTries @usu

SELECT @status
END